### ISSUE TITLE
TargetNullValue 'XAMLMarkupExtensions.Base.BindingValueProvider' after version update

### ISSUE THREAD

**Issue by SergeySSmirnov** [XAMLMarkupExtensions/XAMLMarkupExtensions#102]
I updated the WPFLocalizationExtension nuget package from 3.6.1 to 3.8.0.
In this case XAMLMurkupExtensions automatically were updated from 1.9.0 to 2.0.0.
After that at "XAML bindings error" window I've got few errors and warnings like:

`TargetNullValue 'XAMLMarkupExtensions.Base.BindingValueProvider' (type 'BindingValueProvider') cannot be converted for use in 'Text' (type 'String'). BindingExpression:Path=Value; DataItem=null; target element is 'TextBlock' (Name=''); target property is 'Text' (type 'String') null`

`Fallback value 'XAMLMarkupExtensions.Base.BindingValueProvider' (type 'BindingValueProvider') cannot be converted for use in 'Text' (type 'String'). BindingExpression:Path=Value; DataItem='MainViewModel' (HashCode=53020390); target element is 'TextBlock' (Name=''); target property is 'Text' (type 'String') null`

`Warning: Property Value not found for object type {MyViewModel}`

My XAML code like:
`
<TextBlock Text="{Binding IPAddress, FallbackValue={lex:Loc NotConnected}, TargetNullValue={lex:Loc NotConnected}}" />
`

I found that broken changes locate at 'if' block started at [NestedMarkupExtension.cs](https://github.com/XAMLMarkupExtensions/XAMLMarkupExtensions/blob/7511259ef53c18073f7bc194ddad2ac5bdcf542a/src/Base/NestedMarkupExtension.cs#L190).

If I comment out lines 190-195 all works fine.

Win 10, .Net Framework 4.8.

**Comment by Karnah** [comment]
Hello, @SergeySSmirnov.
I added target property check and now this condition won't be `true` for `FallbackValue` and `TargetNullValue`. But I got next error when I changed current culture:

> InvalidOperationException:'System.InvalidOperationException: Binding cannot be changed after it has been used.

Did it really work before?

**Comment by SergeySSmirnov** [comment]
I checked.
Line above works properly, but line like < ...={lex.Loc {Binding ...}} ... /> not work (with the error that you describe).

**Comment by konne** [comment]
@SergeySSmirnov I have published a new release with the included changes.
@Karnah is there a way to solve the other issue from Sergey?
