### ISSUE TITLE
NestedMarkupExtension doesn't work properly anymore..

### ISSUE THREAD

**Issue by DarkCloud14** [XAMLMarkupExtensions/XAMLMarkupExtensions#13]
Hi,

I'm using WPFLocalizeExtension which again uses XAMLMarkupExtensions, recently I switched to a new version of WPFLocalizeExtension which then again pulled in the latest XAMLMarkupExtensions v1.3.0.

Now I've the problem that one of their extensions (LocText) doesn't work properly with nesting anymore.
See [this](https://github.com/SeriousM/WPFLocalizationExtension/files/1939246/LocalizeTest.zip) sample project.

In that sample project I use LocText nested in LocText and that worked fine with v3.0.1 of WPFLocalizeExtension and XAMLMarkupExtensions but with the latest versions it doesn't anymore.
After debugging a bit I figured that it's enough to switch XAMLMarkupExtensions to v1.3.0 while still using WPFLocalizeExtension at v3.0.1 to run into this problem.

After further debugging I found out that the change made with [this commit](https://github.com/MrCircuit/XAMLMarkupExtensions/commit/cdd452fdd3a074f2fb1ac2031cd1f12e78fd13c5) leads to the problem.

Now is this commit correct for what it should do or is IsConnected returning the correct result?!
Ok why am I asking this question?! Lets have a look at the following line of the above mentioned sample project:
```xaml
<Button Content="{lex:LocText StringFormatTest,
                                               FormatSegment1={lex:LocText StringFormat1},
                                               FormatSegment2={lex:LocText StringFormat2}}" />
```

So we've Content as the EndPoint, LocText StringFormatTest is nested inside it, LocText StringFormat1 and LocText StringFormat2 are both nested inside LocText StringFormatTest.

Now if I debug I see that in NestedMarkupExtensions ProvideValue function the LocText StringFormat1 object is added as a listener to NestedMarkupExtension.EndpointReachedEvent and after that I would expect that LocText StringFormat2 object is added as a listener too.

Of course that is done but through the change of the IsConnected check it removes the weakreference of LocText StringFormat1 object first and so LocText StringFormat1 wouldn't get notified when the EndpointReachedEvent gets fired.

And the next thing that happens is that LocText StringFormat2 gets removed too as in a last step LocText StringFormatTest object is added as a listener and again the IsConnected check returns false which leads to the removal of LocText StringFormat2 object as a listener.

As LocText StringFormatTest is an Endpoint and StringFormat1 + StringFormat2 aren't but there TargetObject is StringFormatTest, they should get informed about the EndpointReached event or am I wrong?

--- EDIT ---
~~Shouldn't IsConnected return true too if the listeners EndPoint and the EndPoint of the already added listeners is equal or shouldn't it at least be consindered as a valid result if they aren't connected to the same sub property?!~~

~~Or in case IsConnected is working as desired shouldn't at least the check to remove the tested target as an EndPointReachedEvent listener get reworked?!~~

The main problem in this case is that the localization of sub properties (FormatSegment1, FormatSegment2 etc.) won't work anymore as at the first run the endpoint is null and as the EndPointReachedEvent isn't invoked for these properties anymore they also won't get localized anymore as soon as the endpoint was reached.

Previously in v1.2.2 of XAMLMarkupExtensions these segments were localized correctly as soon as the EndPointReached event was fired and so the endpoint was passed.
--- EDIT ---

Sorry for the long text but I hope someone with more knowledge here understands my problem and knows a good solution for it.

**Comment by DarkCloud14** [comment]
Ok I've forked the code, had a look at your sample application TestWPF and I would say that even that application doesn't work properly anymore or at least works as expected?!

If I look at the following line of TestWPFs MainWindow.xaml
```xaml
<Label Grid.Row="0" Content="1st Row"
 Background="{ext:AddAlpha Alpha=125, Brush={ext:AlternatingGridColor ColorEven=Red, ColorOdd=Green}}" />
```

I see that the EndPoint Background has two NestedMarkupExtension based extensions attached or better one is directly attached to the endpoint and the other one is attached to a property of AddAlphaExtension class.

Now AddAlphaExtensions function UpdateOnEndpoint returns false but AlternatingGridColorExtension returns true but due to the change of [this commit](https://github.com/MrCircuit/XAMLMarkupExtensions/commit/cdd452fdd3a074f2fb1ac2031cd1f12e78fd13c5) it'll never be updated when the EndPoint is reached as the modification of this check will lead to the removal of AlternatingGridColorExtension object as listener as soon as AddAlphaExtension object is added as a Listener.

Even before the change of the above mentioned commit I wouldn't be sure anymore if it's correct to remove a listener if it tells via UpdateOnEndpoint that it wants to be informed if the endpoint was reached.

So in which cases should the AddListener method of EndpointReachedEvent class really remove a previously added listener?!

**Comment by SeriousM** [comment]
Hi @DarkCloud14, thank you for investigating into this problem! I'M not a WPF developer anymore and want to ask you to solve the problem.
I don't know if @MrCircuit is available anymore as I didn't had contact with him for 2 years now...

**Comment by DarkCloud14** [comment]
@SeriousM I see ok thanks for the answer, I'll try my best to get this solved then.

**Comment by SeriousM** [comment]
It would be awesome if you could share your solution :)

**Comment by DarkCloud14** [comment]
@SeriousM Ok I think I've a better idea now why someone would change the IsConnected check in [this commit](https://github.com/MrCircuit/XAMLMarkupExtensions/commit/cdd452fdd3a074f2fb1ac2031cd1f12e78fd13c5) but in my opinion this was wrong as it will break the UpdateOnEndpoint functionality.

The main problem however is that the listeners list of EndpointReachedEvent class is filled but never cleared up until the GC decides to run and collect garbage..
Also it's just a flat list and in case the end point is reached every listeners in that list gets informed even if the listener itself is in a different Window.
Another problem in my opinion is, that even if the derived markup extension doesn't want to do anything when the endpoint is reached it'll be added to the listeners list.

I made a few changes now to NestedMarkupExtension class but only the .Net 4.0 build will gain most of the performance improvements as .Net 3.5 doesn't have the used IRootObjectProvider  service provider.

One thing I've done is to add a abstract property WillUpdateOnEndpoint which is used to only add the extension to EndpointReachedEvent listeners if it returns true. This change will require an adjustement but I didn't want to use the UpdateOnEndPoint function as someone might check the given end point and decides according to that if it returns true or false..

Another change was that EndpointReachedEvent listeners is now a Dictionary instead of a list.
The key is at least for .Net 4.0 the rootobects hash code and you can get the rootobject using the IRootObjectProvider service provider.
If the rootobject is of type Window I also subscribe the Closed event once to remove the rootobject and its listeners of the EndpointReachedEvent listeners dictionary.

All changes are in my forked repository, should I create a pull request to get the changes back into this project or aren't you (@SeriousM) able to handle that?

BTW I also made adjustements on the WPFLocalizationExtension project which I forked. This includes changes to make it a multi framework build so you'll get a .Net3.5 and .Net4.0 compatible dll and of course the necessary implementation of the WillUpdateOnEndpoint property.

I didn't change the NuGet package version of XAMLMarkupExtensions as I won't be able to push a new version to NuGet so that adjustement would have to be done as soon as a new version of XAMLMarkupExtensions is online..

**Comment by xmedeko** [comment]
@DarkCloud14 note, the change is commented in #9.

**Comment by Hollowman1985** [comment]
@DarkCloud14 do the changes you made in your fork also fix the problem described in #9? I don't have the time right now to test you fork. I hope I have time to test it in a few weeks...

**Comment by DarkCloud14** [comment]
@Hollowman1985 well if you use the .Net 4.0 version I would say the problem should be fixed as there only the necessary objects will be notified and an automatic disposal/cleanup is done as soon as the parent window will closed.

For .Net 3.5 it would behave again as before your change to fix the EndPointReached behaviour.

Depending on the markup extensions used it might be less of a problem as I introduced the new property WillUpdateOnEndpoint which must be implemented and only if this is true the markup extension object will be added to the EndpointReachedEvent listeners...

But still I would say that you should do your own tests.

For my application were I heavily use WPFLocalizationExtension it had a big impact and fixed the performance problems.

But therefore I also modified the WPFLocalizationExtension project to implement the necessary change and also create a .Net 3.5 + .Net 4.0 assembly.
In my project I use the .Net 4.0 assembly to also have the automatic disposal + cleanup when a window gets closed..

**Comment by konne** [comment]
@DarkCloud14 can you make a pullrequest
great would be a change to the new csproj because this supports out of the box multitarget and nuget packages

**Comment by Hollowman1985** [comment]
@DarkCloud14 do you plan to pull your changes in the WPFLocalizationExtension too? Because I am in the same situation using the WPFLocalizationExtension where I got performance issues with previous versions of this library...

**Comment by konne** [comment]
@Hollowman1985  and @DarkCloud14 
I will try to discuss this today with MrCircuit and make test arround your PR in the next days.
After that we should go the next step to integrate it into WPFLocalizationExtension

**Comment by DarkCloud14** [comment]
@Hollowman1985 well I would but as it depends on XAMLMarkupExtensions I would wait until a official package with this fix is out.

Also when I think about it, if you've a single window situation where you just switch user controls you could run into performance problems again even with .Net 4.0 as my current solution puts objects into a dictionary and the key is the root objects hash retrieved of the IRootObjectProvider service provider.
In a single window situation this root object hash would be always the same I guess, also the automatic close event subscription + root object base cleanup is done for each root object only if it's of type Window...

Would it make sense to add another static method to NestedMarkupExtensions class which would allow to trigger a cleanup of the whole EndpointReachedEvent listeners manually?!

Or would it make sense instead to add a property over which you could specify the root object for the NestedMarkupExtension via XAML and fallback to my current implementation if it isn't specified at all?!
In that case it might also be usefull to have another property with which you can specify the event that the NestedMarkupExtension should subscribe to, to get a automatic cleanup as soon as that control closed?!

Or does someone of you have another idea how to solve the problem that the EndpointReachedEvent listener doesn't just fill up but also gets cleaned up again as soon as the parent controls are closed/gone?!

I think the problem could also be solved by triggering a GC collect at some point but that isn't really a solution in my opinion..

**Comment by konne** [comment]
@DarkCloud14 we have move the repo because MrCircuit don't have time for this anymore.
I restructed everything and already updated the build process and changed to a gitflow with the branches.

I really like to submit ASAP a alpha nuget package, but  still see no reason why we have to make this release as a breaking change. (every subclass has to implement the WillUpdateOnEndpoint property).
Why we can not make a default value for the old behauvior and you can override it if you want it different.
Please can you make a new PR to the development branch

**Comment by SeriousM** [comment]
Hi @konne, welcome! @mrcircuit didn't told me anything about this change, sorry about that.
How's your experience with WPFLocalizationExtension?

**Comment by konne** [comment]
@SeriousM I have very good experience  with WPFLocalizationExtension because the most of the changes about 8 years ago in XAMLMarkupExtensions  I developed together with MrCircuit.
I also use  WPFLocalizationExtension in my daily work for https://www.senseexcel.com/ so I know it very well.

**Comment by xmedeko** [comment]
@konne Thanks for taking care of this project. OT: I recommend you much [lighter GitHub flow](https://guides.github.com/introduction/flow/). It's sufficient for this project and most of GitHub users (contributors) are accustomed to it. Do not want to start a flamewar, just a tip for you.

**Comment by DarkCloud14** [comment]
@konne Sorry for my late response, looks like the changes were already merged and so I can't create a new pull request.
The reason I didn't set a default value for WillUpdateOnEndpoint at all was to make it clear that there is something to do and whoever is using the extension gets to know that, even without reading changelogs or so...

If you set a default value to get the old behaviour back it'll be true but that might automatically introduce performance problems (see #9) again as every extension will be added to the EndpointReachedEvent listeners again and later on informed even if they really don't do anything when the end point is reached.

In the end it's of course up to you to change the WillUpdateOnEndpoint property to have a default value instead. I also didn't use the already existing function UpdateOnEndpoint as it is called everytime an endpoint is reached in case the extension is a EndpointReachedEvent listener. I wanted to have something seperate here as I don't know what already existing projects will really when UpdateOnEndpoint is reached, maybe they decide at runtime when the function is called to update or not and so return true or false here.

As mentioned in my post 4 days ago the situation to run into performance problems isn't completely solved even with the changes I made.

**Comment by konne** [comment]
@DarkCloud14 I send you an private email, I would like to discuss the things on the phone and document the changes after that here

**Comment by DarkCloud14** [comment]
A short update, @konne did some additional tests and found other problems with my solution. It works fine with WPFLocalizationExtension but other extensions might not work correctly anymore..

We currently try to figure something out that'll help to solve this issue properly and issue #9 as good as possible without breaking functionality again.

**Comment by konne** [comment]
Just as a general info @DarkCloud14 and me working at the moment on this issue.
We plan at the moment to have a better use of the IRootObjectProvider to get even the root of UserControls,... We will update everybody after we have added a new version to test.

**Comment by konne** [comment]
@DarkCloud14 @xmedeko @Hollowman1985 I just published a pre Nuget package. Please can you test if you issues are solved. many thanks to @DarkCloud14 for his support

**Comment by Hollowman1985** [comment]
@konne I will do so on friday an give you feedback on that day too. To be clear, my issue is related to #9 .

**Comment by DarkCloud14** [comment]
@Hollowman1985 [The commit](https://github.com/MrCircuit/XAMLMarkupExtensions/commit/cdd452fdd3a074f2fb1ac2031cd1f12e78fd13c5) you made to solve issue #9 (at least I guess you made it therefore) lead to this issue but with the new version also #9 should be fixed or at least mitigated if you use the .Net 4.0/4.5 dlls.

Unfortunately there isn't a fix for issue #9 using .Net 3.5 as the service providers used to fix/mitigate the performance problem aren't available here.

I say mitigate, as the performance drop depends on the amount of nested markup extensions used in a framework element/window.

There is still potential to optimize the performance but this is a first step to have NestedMarkupExtension working properly again and also have a better performance if .Net 4.0/.Net 4.5 dlls are used.

**Comment by Hollowman1985** [comment]
@DarkCloud14 Thank you for explaining this. In our projects we use .NET 4.5.2 right now, so you're changes should help us in our projects. As I said tests are done on friday. I come back to you after that.

**Comment by Hollowman1985** [comment]
@DarkCloud14 @konne Hi guys, first of all sorry for the late reply. I tested nuget package version 1.4.0-alpha0032 with my .NET application 4.5.2 and the performance issue mentioned in issue #9 seems to be gone. I also didn't find any issue in my cases where WPFLocalizeExtension is used, but to be clear we have no use case right now where we use nested localizations like it is described in the first post.
