### ISSUE TITLE
Check if EndpointReachedEventArgs.Handled can be removed

### ISSUE THREAD

**Issue by konne** [XAMLMarkupExtensions/XAMLMarkupExtensions#16]

**Comment by konne** [comment]
@Karnah 
I think this issue is related to the last discussion, please can you check it,
I just copied that issue from an old list, so this is older than Jun 2018

**Comment by Karnah** [comment]
@konne, I found issue where it modified - in [WPFLocalizationExtension](https://github.com/XAMLMarkupExtensions/WPFLocalizationExtension/issues/79)
I think it can be marked using `ObsoleteAttribute` in next release and removed after it.
