### ISSUE TITLE
Exception on ClearBindings

### ISSUE THREAD

**Issue by strohhaecker** [XAMLMarkupExtensions/XAMLMarkupExtensions#30]
We've experienced an InvalidOperationException (stacktrace added at the bottom) when e. g. calling BindingOperations.ClearBinding. The message is (sorry for the localized message) : Sobald ein DataTrigger-Objekt verwendet wird (versiegelt ist), kann es nicht mehr geändert werden. [means SetValue cannot be called on sealed objects].

See the following pull-request for a possible fix: https://github.com/XAMLMarkupExtensions/XAMLMarkupExtensions/pull/29

Ein Aufrufziel hat einen Ausnahmefehler verursacht.
   bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   bei System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   bei System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   bei System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   bei XAMLMarkupExtensions.Base.NestedMarkupExtension.UpdateNewValue(TargetPath targetPath)
   bei XAMLMarkupExtensions.Base.NestedMarkupExtension.UpdateNewValue(TargetPath targetPath)
   bei WPFLocalizeExtension.Extensions.LocExtension.ResourceChanged(DependencyObject sender, DictionaryEventArgs e)
   bei WPFLocalizeExtension.Engine.LocalizeDictionary.DictionaryEvent.Invoke(DependencyObject sender, DictionaryEventArgs args)
   bei WPFLocalizeExtension.Providers.ParentChangedNotifierHelper.<>c__DisplayClass0_0`1.<GetValueOrRegisterParentNotifier>b__0()
   bei XAMLMarkupExtensions.Base.ParentChangedNotifier.ParentChanged(DependencyObject obj, DependencyPropertyChangedEventArgs args)
   bei System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)

**Comment by konne** [comment]
@strohhaecker thanks, I will take

**Comment by konne** [comment]
@strohhaecker I have generated a new NUGET PRE release. Please check XAMLMarkupExtensions.1.6.0-alpha0007 if it works I will create a Release Nuget

**Comment by strohhaecker** [comment]
> 
> 
> @strohhaecker I have generated a new NUGET PRE release. Please check XAMLMarkupExtensions.1.6.0-alpha0007 if it works I will create a Release Nuget

alpha0007 does not contain the fix regarding this issue, I've tested it and it does not work (did you intend to add the pull-request that adds the sealed check to alpha0007? then something went wrong)

**Comment by strohhaecker** [comment]
> @konne sorry for being late at this, just checked the NuGet packages code and @strohhaecker is right, something went wrong as this version doesn't contain the merged fix for this issue.
> 
> BTW the only thing I would have changed is the two line if statements as in both cases the two checks are short and should have been ok on one line.

How do you want to proceed with this? Shall I issue another pull request and link it here to remove the one check and adapt the if-styling?
Thanks for checking this out!

**Comment by strohhaecker** [comment]
> @strohhaecker a new nuget is online please check

It does work, thanks! Will WPFLocalizationExtension be updated to use the new XAMLMarkupExtensions? Since for testing I had to self-compile WPFLocalizationExtension and use the updated nuget alpha0013 of XAMLMarkupExtensions (maybe because of the version gap to 1.6.0).

Thanks!

**Comment by konne** [comment]
@strohhaecker, thanks for the feedback, yes I will update WPFLocalizationExtension in the next days
hopefully tomorrow

**Comment by DarkCloud14** [comment]
@strohhaecker @konne Just had a look at the code again today, especially at the SetPropertyValue method.

Wouldn't the following code also lead to the problem and so shouldn't we adjust the code to check at the beginning as you already mentioned in the pull request? We could add an exception for the IsAssignableFrom IList case...
```C#
  // Set the value.
  if (info.TargetProperty is DependencyProperty)
    ((DependencyObject)info.TargetObject).SetValueSync((DependencyProperty)info.TargetProperty, value);
  else
  {
```
If it's ok I'll do some testing tomorrow or at the latest on Saturday, just to be sure that this wouldn't lead to the same problem or can you already say that this wouldn't be the case?

**Comment by konne** [comment]
@DarkCloud14 thanks, please follow up in PR #31
@strohhaecker please have a look at this PR

**Comment by konne** [comment]
@strohhaecker @DarkCloud14 a new preRelease Nuget is online. I will now also make a preRealease of LocExtension XAMLMarkupExtensions.1.6.0-alpha0019.nupkg If there is now issue in the next week I will make a new Release
