### ISSUE TITLE
Critical performance issues when using merged assemblies

### ISSUE THREAD

**Issue by oopbase** [XAMLMarkupExtensions/XAMLMarkupExtensions#9]
We are currently using XAMLMarkupExtension and WPFLocalizationExtension to localize our software. Furthermore, we use SmartAssembly to merge and obfuscate the assemblies. After merging the assemblies, we are experiencing huge performace issues when using the software. Before localizing the software, this issue didn't exist.
However, we used dotTrace to find out what's going on. For some reason, there are _more_ and also time consuming XAMLMarkupExtension calls within the merged and obfuscated software, which cause the preformance issue. This issue doesn't exist, when we don't merge and obfuscate the software. Specifically, this issue occurs when merging the assemblies. Unfortunately, SmartAssembly only supports code obfuscation on merged assemblies.

So, maybe this is a problem with SmartAssembly, but still:
Has anyone, _maybe_ ( @SeriousM, @MrCircuit...) an idea, why those (random) XAMLMarkupExtension-calls exist within the merged Assemblies?

![issue](https://cloud.githubusercontent.com/assets/11479694/13636908/a56b2d86-e604-11e5-9944-9e4a81728487.png)

**Comment by konne** [comment]
I think you don't have to merge and obfuscate all assemblies. You can make it with you assemblies and not with external like XAMLMarkupExtensionm,,,
All in all I don't see the point to obfuscate wpf apps. I always seperate the business logic and the view and only obfuscate the business logic.

**Comment by oopbase** [comment]
@konne I do absolutely agree with you. Unfortunately, the software grew for over six years now. It is planned to separate everything, but currently it is just not possible due to the complexity and due to a lot of dependencies between all software modules.

**Comment by jstevenson72** [comment]
Have you tried using the exclusion in SmartAssembly?  You can mark the namespaces where you are doing the xaml work and exclude them from the obfuscation.

**Comment by Hollowman1985** [comment]
Hello Guys,

Is there any new on this point?

I stumpled upon the exact same performance issue in a different scenario (see attached picture). In my case I created a Grid with some ItemsControl which are using DataTemplates and the WPFLocalizationExtension for the translation of some enumerations and text. The content is dynamically created in the ViewModel and defined in an ObservableCollection. Depending on the user interaction and on the lifetime of the application the ObservableCollection will be overriden many times. The performance issue gets worse with the count of the creation of new objects.

![Uploading 2017-10-18 14_41_32-Syskron.SequenceTool.Gui.Application - 18.10.2017, 14_18_22 – JetBrains dotTrace.png…]()

**Comment by SeriousM** [comment]
Hi @Hollowman1985,
as you can see the project is maintained on a very low level. Could you help us getting this bug fixed by contributing?

Thank you very much!

**Comment by Hollowman1985** [comment]
Hi @SeriousM,
I will try my best! Come back to you soon...

**Comment by Hollowman1985** [comment]
First time first try on Github. Pull request is there. Can you push a new version to nuget soon?

I simply changed one line and now the listeners are cleaned correctly and the count of it is not encreasing anymore. I tested it with the latest version of the WPFLocalizationExtension and it works fine!

**Comment by xmedeko** [comment]
@Hollowman1985 your fix maybe broke another functionality, see #13

**Comment by Hollowman1985** [comment]
Hello Guys,
I am sorry that my change broke functionality on your side. I used this fixed in my application for a long time and in my scenarios I couldn't find any problems with it. I am sorry that I didn't had the time to test the whole thing around.

As far as I can see in issue #13 DarkCloud14 found a way to work around both issues, but right now I dont have the time to test his forked solution.

**Comment by konne** [comment]
@oopbase @jstevenson72 please test the new pre Nuget packages wich should solve this issues and also fixes #13

**Comment by Hollowman1985** [comment]
@konne With version 1.4.0-alpha0032 tested in my .NET application 4.5.2 the AddListener function i mentioned above consumed up to 2% in my used case. Seems fine for me now. I can't test the case @oopbase described.
